### ISSUE TITLE
High CPU usage with labwc+vmware

### ISSUE THREAD

**Issue by knm100** [nwg-piotr/nwg-hello#10]
environment：Vmware 17.5.1+Arch+labwc 7.1+nwg-hello 0.19
More than 50% CPU usage before login or after logout
Once logged, the CPU usage quickly drops to below 3%.

**Comment by nwg-piotr** [comment]
Well, I don't test in other environment than Hyprland or sway on bare metal. Sorry, I won't dig into it.
