### ISSUE TITLE
label changes in template file not shown

### ISSUE THREAD

**Issue by fybx** [nwg-piotr/nwg-hello#19]
Hi!

I have made some changes to the default template, here's the diff:
```
42c42
<                             <property name="label" translatable="yes">いらっしゃいませ</property>
---
>                             <property name="label" translatable="yes">Welcome!</property>
67c67
<                             <property name="label" translatable="yes">Monday, 13 January</property>
---
>                             <property name="label" translatable="yes">Monday, 13. January</property>
```

I updated the field "template-name" in `/etc/nwg-hello/nwg-hello.json` to "/etc/nwg-hello/navi.glade" and also just "navi.glade", but none of them worked.

Sorry in advance if I missed something - I'm very tired 😄

**Comment by mike-lloyd03** [comment]
I'm having this problem too. On archlinux, I copied `/usr/lib/python3.12/site-packages/nwg_hello/template.glade` to `/etc/nwg-hello/mike.glade`. I changed:

```xml
<property name="label" translatable="yes">Welcome!</property>
```

to

```xml
<property name="label" translatable="no">Log in</property>
```

 And updated `nwg-hello.json` to this:

```json
{
    ...
    "template-name": "mike.glade",
    ...
```

But the page still shows "Welcome!"

**Comment by nwg-piotr** [comment]
The label value in the template is just initial. Actual values come from [language files](https://github.com/nwg-piotr/nwg-hello/tree/main/nwg_hello/langs), so you can't really change them.

**Comment by fybx** [comment]
> The label value in the template is just initial. Actual values come from [language files](https://github.com/nwg-piotr/nwg-hello/tree/main/nwg_hello/langs), so you can't really change them.

So editing a lang file and recompiling would achieve the result we wish to achieve, right?

**Comment by nwg-piotr** [comment]
Yes. Honestly, I could have provided them just in `/usr/share/nwg-hello/`, my bad.

**Comment by nwg-piotr** [comment]
The patch above allows to upload your own [lang files](https://github.com/nwg-piotr/nwg-hello/tree/main/nwg_hello/langs) to `/etc/nwg-hello/`.

**Comment by fybx** [comment]
Thanks a lot!
