### ISSUE TITLE
Unable to input condition and box selection highlight improvement 

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-hello#25]
**Problems**
1. After start or logout I cant  type until I move the mouse anywhere so that the cursor appears
2. The highlighted box is barely visible

**Possible solutions**
1. Would be better if any box is already selected so I can tab through options
2. Increase the focused box outline width

**Comment by nwg-piotr** [comment]
Impossible on Hyprland 0.43.0. Try running nwg-hello on sway. Closing as a duplicate of #20.
