### ISSUE TITLE
[Help needed] Can I change the format of date?

### ISSUE THREAD

**Issue by Vescrity** [nwg-piotr/nwg-hello#28]
Hi, i'm trying to change the format of the date, but i failed.  

Change `lang` won't change the format of `date`. Then i tried to modify the template, and it still shows the date in format like `Monday, 13, Janurary`. Maybe the line of `<property name="label">` just do nothing?

**Comment by nwg-piotr** [comment]
You can't, it's fixed:

```python
    def update_time(self, now):
        self.lbl_clock.set_text(f'{now.strftime("%H:%M:%S")}')
        self.lbl_date.set_text(f'{now.strftime("%A, %d. %B")}')
```

We would need some way (a flag?) to pass other formats.

**Comment by nwg-piotr** [comment]
Sorry, this was a mistake. It should be configured in the nwg-hello.json config file. I'll get back to it tomorrow.
