### ISSUE TITLE
[Feature] Make the layer and keyboard_mode configurable

### ISSUE THREAD

**Issue by Vescrity** [nwg-piotr/nwg-hello#30]
In `ui.py`, line 152, the following code is used:

```python
GtkLayerShell.set_layer(self.window, GtkLayerShell.Layer.OVERLAY)
GtkLayerShell.set_keyboard_mode(self.window, GtkLayerShell.KeyboardMode.EXCLUSIVE)
```

I believe setting the window to `OVERLAY` and `EXCLUSIVE` mode may not be necessary. For instance, if I modify the `suspend_cmd` to:

```bash
kdialog --yesno "Are you sure?" && systemctl suspend
```

This should displays a dialog window, but in `OVERLAY` mode, the dialog cannot be shown properly. Therefore, I suggest that these settings could be configurable in the `nwg-hello.json` file to allow for flexibility.

**Comment by nwg-piotr** [comment]
Sure, why not?
