### ISSUE TITLE
nwg-hello.css expects or supports only jpg files and not png files

### ISSUE THREAD

**Issue by prabusw** [nwg-piotr/nwg-hello#4]
I tried nwg-hello and found nwg-hello.css expects or supports only jpg files and not png files. When i changed the background-image: url("/usr/share/nwg-hello/nwg.jpg") to whatever option it was not working. Only after the file format was changed to jpg, the change worked. Please confirm if this is by design.

**Comment by nwg-piotr** [comment]
I don't confirm: both jpg and png files should work. However, there was a bug in default .css file patch, so the `/etc/nwg-hello/nwg-hello.json` path would not work. Fixed in a3251c9. I'll release v0.1.6 tonight.

**Comment by nwg-piotr** [comment]
Should be resolved in https://github.com/nwg-piotr/nwg-hello/releases/tag/v0.1.6.
