### ISSUE TITLE
fails to start due to python errors

### ISSUE THREAD

**Issue by Noctivivans** [nwg-piotr/nwg-hello#7]
Hi,
I've installed and configured nwg-hello the way mentioned in README, but it keeps falling back to terminal with errors as seen on screen (they are not being logged even with -l switch, hence the photo)
![P_20240321_131836](https://github.com/nwg-piotr/nwg-hello/assets/6827560/b21dfcaf-24a5-4c16-92bc-0a13624a25eb)
I've created log by adding -l switch to /etc/nwg-hello/sway-config nwg-hello command:
[nwg-hello.log](https://github.com/nwg-piotr/nwg-hello/files/14695108/nwg-hello.log)
Any ideas what may be the cause? My system (Archlinux) is fully updated, including AUR packages.
Thanks in advance :)

**Comment by nwg-piotr** [comment]
Well, I haven't seen such a crash so far. Do you by any chance have a user with a name that contains some non-ASCII characters?

**Comment by Noctivivans** [comment]
I don't have non-ASCII characters in account name or home directory, however my name includes "ł", and I am using it in account description (full name)

**Comment by nwg-piotr** [comment]
Thanks to you for reporting. :)
